
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

// 1. Import the Theme Context Provider
// import { ThemeContextProvider } from "@/ThemeContext"; // Adjust path if necessary!

import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import ThemeContext from "@/ThemeContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* 2. Wrap the application content with the ThemeContextProvider */}
        {/* <ThemeContext> */}
          <NavBar />
          {children}
          <Footer />
        {/* </ThemeContext> */}
      </body>
    </html>
  );
}
